name: multi_pro_services
description: A real-time on-demand multi-service platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: any
  google_maps_flutter: any
  google_maps_flutter_web: any
  google_fonts: ^6.1.0
  provider: ^6.0.5
  go_router: any
  intl: ^0.18.0
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
